# Generated by Django 6.0.7 on 2026-07-24 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rt_app', '0002_alter_order_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
